language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
after_success: export ANGULAR_NODE_COVERAGE=1; jscoverage --no-highlight src src-cov; mocha test/* -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js; unset ANGULAR_NODE_COVERAGE;
